# Site settings
title: iCalGenerator CLI Documentation
description: "iCalGenerator CLI consumes JSON containing calendar event data and generates an iCalendar file."

author:
  name: Joe Paquette
  email: paqdev76@protonmail.com
keywords: "node, TypeScript, JSON, iCalendar, iCal, ics, generator"
repo: "https://github.com/Paqrat76/ical-gen-app"

plugins:
- jekyll-remote-theme

# Theme settings
# remote_theme: pages-themes/slate@v0.2.0

remote_theme: zendesk/jekyll-theme-zendesk-garden@v0.7.3
search_enabled: false
version: false
auto_page_title: true
mermaid_enabled: false
sidebar:
  - label: "Documentation"
    children:
      - usage-doc
      - schema-doc
